const cards = [

  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Клавиатура",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },
  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Баба-клава",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Каменные кнопки",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Памятник клавиатуре",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },   {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Большие кнопки",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },
  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "С кнопки прыг",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Каменный пробел",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },  {
    "_id": "64be8d74aafa730338c19c9c",
    "country": "ddd",
    "director": "dfb",
    "duration": 122,
    "year": "2000",
    "description": "uuiiopp",
    "image": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "trailerLink": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.mp4",
    "thumbnail": "https://tripplanet.ru/wp-content/uploads/europe/russia/ekaterinburg/art-object-keyboard.jpg",
    "owner": "64bcda6a92def2627988bad9",
    "movieId": 45896357,
    "nameRU": "Нажми cntrl+shift",
    "nameEN": "gjkbnkjdg",
    "__v": 0
  },

]

export default cards;
